// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgg2xF38FRVu6T52opFQNDtiOyIUjmj5g',
    appId: '1:702974145232:web:e6a0728480503bd53064d5',
    messagingSenderId: '702974145232',
    projectId: 'graduationproject-4f4ab',
    authDomain: 'graduationproject-4f4ab.firebaseapp.com',
    storageBucket: 'graduationproject-4f4ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIqz2zrzquYbpsvr2bmwymkUH3xWe2nFE',
    appId: '1:702974145232:android:3bafeb5d8fca43c43064d5',
    messagingSenderId: '702974145232',
    projectId: 'graduationproject-4f4ab',
    storageBucket: 'graduationproject-4f4ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC57XZUEzn9jfYH5YlIXmc236TMusE74lc',
    appId: '1:702974145232:ios:c4abfc74de61cad03064d5',
    messagingSenderId: '702974145232',
    projectId: 'graduationproject-4f4ab',
    storageBucket: 'graduationproject-4f4ab.appspot.com',
    iosBundleId: 'com.example.splashOnboardingTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC57XZUEzn9jfYH5YlIXmc236TMusE74lc',
    appId: '1:702974145232:ios:c4abfc74de61cad03064d5',
    messagingSenderId: '702974145232',
    projectId: 'graduationproject-4f4ab',
    storageBucket: 'graduationproject-4f4ab.appspot.com',
    iosBundleId: 'com.example.splashOnboardingTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgg2xF38FRVu6T52opFQNDtiOyIUjmj5g',
    appId: '1:702974145232:web:62277a77f4a45d9c3064d5',
    messagingSenderId: '702974145232',
    projectId: 'graduationproject-4f4ab',
    authDomain: 'graduationproject-4f4ab.firebaseapp.com',
    storageBucket: 'graduationproject-4f4ab.appspot.com',
  );
}
